### ISSUE TITLE
Erstelle ein Dokument zum API der Deutschen Digitalen Bibliothek

### ISSUE THREAD

**Issue by oe-bayram** [pathob/bilderquiz#2]
Wir möchten Bilder und Gemälden für unser Quiz verwenden. 
Dazu soll bitte zunächst die Nutzung der API und die Liste der nützlichen Daten dokumentiert werden.

**Comment by Nholan** [comment]
Ich werde dieses Problem jetzt angehen. Dazu wollte ich eine kurze Übersicht über die Nutzung der Datenbank geben. Und dann anhand einer Beispielanfrage illustrieren wie wir an unsere Daten kommen können. Falls hier jemand Ergänzungen hat was noch mit rein soll, bitte hier posten.

PS:Ich bin Mirco

**Comment by Nholan** [comment]
So habe ein Dokument geschrieben, das eine Übersicht über die API gibt und zwei Lösungsansätze um an unsere Daten zu kommen. Außerdem habe ich eine Test-php Datei hochgeladen, die verschiedene Requests implementiert um zu zeigen wie das dann im Code aussieht. Die ist in sofern wichtig, da ich es im Dokument vermeide Code anzugeben.

mfg Mirco
